### ISSUE TITLE
UIPageViewController bug and possible workaround

### ISSUE THREAD

**Issue by itchingpixels** [mindsnacks/MSPageViewController#12]
Hi,

I've been using MSPageViewController in one of my projects and found a mysterious crash, related to a bug in UIPageViewController, that you may be interested to look at:

http://stackoverflow.com/questions/14220289/removing-a-view-controller-from-uipageviewcontroller

I have been using this workaround and successfully eliminated the crashes.

**Comment by dmzza** [comment]
Thanks for the tip, but MSPageViewController is really meant for simple carousels created in a Storyboard. I don't think we're gonna tackle that specific problem.
