### ISSUE TITLE
Remove animation like curl while scroll or naviagete to next view controller

### ISSUE THREAD

**Issue by ananarola** [mindsnacks/MSPageViewController#13]
Hi..
I am using MSPageViewController for page view controller and i am newbie for this.
I want to remove animation while display when we scroll or simply navigate to next page.
How can i achive this.

Thanks in advance

**Comment by dmzza** [comment]
If you are trying to change the transition style programmatically, I don't think there is a way. MSPageViewController is only meant to be used with a Storyboard, and in that case, it is in the inspector for the page view controller: 
![](http://i.stack.imgur.com/2oTMH.png)
